### ISSUE TITLE
When Registering, Search Country Codes by Country Code

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1832]
Country Code search currently only matches country name - not the country code itself.  You should be able to search for +44 (UK) by typing 44.

**Comment by NicolasCGN** [comment]
In 2.8.0.5 (also 2.8.0.4) is not possible to search the country by entering the first characters of its name.

**Comment by charlesmchen** [comment]
Thanks @NicolasCGN .  This will be fixed in a forthcoming release.

**Comment by charlesmchen** [comment]
@NicolasCGN This is fixed and will ship in a forthcoming release.

**Comment by NicolasCGN** [comment]
Hmmmm. I'm still not able to filter countries in beta 2.8.3.0. No matter if I write the beginning of the country's name or the telephone prefix.

**Comment by michaelkirk** [comment]
This will be fixed in 2.9.0

**Comment by michaelkirk** [comment]
In https://github.com/WhisperSystems/Signal-iOS/commit/a264d9aa9b4d37655dc4648919c971bb3a068a61
