### ISSUE TITLE
Music won't resume playing after playing a received voice/audio message

### ISSUE THREAD

**Issue by likyng** [WhisperSystems/Signal-iOS#1903]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I am listening to music on my phone. Then, I receive an audio message (from an Android phone) and play it back. The music stops playing. After the voice message is done playing the music won't resume automatically. The expected behaviour (for me) is that the music resumes, like in apps like WhatsApp.

### Steps to reproduce
- Play music
- Play audio message

**Actual result:** Music won't resume playing
**Expected result:** Music resumes when the audio message finishes playing.

### Device info

**Device**: iPhone 6
**iOS version**: 10.2
**Signal version:** 2.9.0

**Comment by michaelkirk** [comment]
Fixed by https://github.com/WhisperSystems/Signal-iOS/pull/2007

Which will be in the 2.11.0 release (or you can try the beta now).

**Comment by likyng** [comment]
@michaelkirk Actually, this issue still persists for me, using Signal version 2.12.2. Same issue with voice recording (Signal will pause playing music while you are recording a voice message but will not resume the music upon voice recording finished).
