### ISSUE TITLE
The height of the text box with draft message doesn't honour the long drafts

### ISSUE THREAD

**Issue by chanying2** [WhisperSystems/Signal-iOS#2241]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The height of the text box with draft message to a contact doesn't honour the long drafts

### Steps to reproduce
- Write a long message to a contact, at least two lines, but do not send yet.
![image](https://user-images.githubusercontent.com/14188774/27309746-a603e38c-554d-11e7-9605-823e55d8ede8.png)
- Go back to main conversations view.
- Open the conversation again with the same contact where you will see the draft text. The text box size is diminished as if the draft text is a single line.  
![image](https://user-images.githubusercontent.com/14188774/27309763-beb4ea48-554d-11e7-9ea2-eb8927e9a787.png)

**Actual result:** The text box height is a single line height.
**Expected result:** The text box height should not be a single line height.

### Device info

**Device**: All
**iOS version**: All
**Signal version:** All

**Comment by kaktusztea** [comment]
2.30.2.16 still has this issue - I can confirm.

**Comment by SpineEyE** [comment]
This is fixed in beta!

**Comment by kaktusztea** [comment]
Sorry, but it is still present in 2.32.2.0...
1. Write a lot of text to Bob (to make it scrollable), but don’t send it
2. Go back to conversation list view
3. Open Bob’s conversation again
4. Tap to draft text box
5. Try to position at the end of the text
(No success)
