### ISSUE TITLE
Disappearing message timer automatically turned off

### ISSUE THREAD

**Issue by TreatyOfRome** [WhisperSystems/Signal-iOS#2284]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The disappearing message timer setting is automatically turned off.

### Steps to reproduce
- I'm (iOS) having a chat with my chatpartner (Android);
- I have set the dissapearing message timer to 1 week;
- System message received that I have set the dissapearing message timer to 1 week;
- We exchange some messages;
- After a while, I receive a system message that my chatpartner has disabled the disappearing message timer;
- My chatpartner receives a system message that I have disabled the dissapearing message timer;
- We both did not disabled the disappearing message timer.

**Actual result:** Disappearing message status changes automatically.
**Expected result:** Disappearing message status remains unchanged.

### Device info
**Device**: iPhone 6S
**iOS version**: 10.3.2
**Signal version:** 2.13.0.16

### Link to debug log
https://gist.github.com/1a6aaaca50aa6b44f9798b12a6b88b08
Debug log is produced 1-5 minutes after automatical disabling of disappearing message timer.

**Comment by TreatyOfRome** [comment]
Additional info: 
- This bug appeared since my update to Signal 2.13.0;
- I have verified safety numbers with my chatpartner (camera+scan);
- Deleting the chat and starting an new chat with disappearing message timer does not solve this bug.

**Comment by michaelkirk** [comment]
Did your friend reinstall? Are either of you using a linked desktop?

**Comment by TreatyOfRome** [comment]
Neither party reinstalled. No linked desktops involved.
Friend has Signal 4.6.1 (Android).

**Comment by michaelkirk** [comment]
Thanks for the details.

From your log, here is where it happened:

https://gist.github.com/anonymous/1a6aaaca50aa6b44f9798b12a6b88b08#file-org-whispersystems-signal-2017-07-03-10-19-log-L800

    2017/07/03 15:57:52:149  [OWSDisappearingMessagesJob] Received remote message which had no expiration set, disabling our expiration to become consistent.

Any idea which message in your conversation history that corresponds to (15:57:52 local time)? Can you provide any details? Any way to get a debug log from your friend at this time?

**Comment by michaelkirk** [comment]
Also, could you ask your friend to update to the latest Signal-Android?

**Comment by TreatyOfRome** [comment]
Friends debug log did not have any data from that time (15:57) anymore. 
Friend has updated Signal-Android to 4.7.4. 
If this bug reappears, I will try to retrieve a debug log from both phones and post them here.

**Comment by TreatyOfRome** [comment]
This time a little different:
1) my friend received a system notification that I had disabled disappearing messages;
2) my friend received a message from me without hourglass;
3) my friend received a system message that I had enabled disappearing messages.
I on the other hand received no notifications and all my messages have hourglasses.

Debug log friend (Android 4.7.4): https://gist.github.com/880174ca888d1294abf7e9fe16acd57e
Debug log me (iOS 2.10.13): https://gist.github.com/aea3f3cb5848a0c35443ed788a4bf800

These three messages happened from 20:06 to 20:07 local time.

**Comment by KevinMBoyd** [comment]
This appears to happen when an iOS user replies from the notification banner. Guessing that the notification banner does not have the ability to set the message expiration or this is not properly configured.

**Comment by TreatyOfRome** [comment]
Yes! I can confirm! This causes the written behaviour.

Another set of debug logs: 
https://gist.github.com/f5782f3c07e03b01ca54c2a8e1e0abff (iPhone, sending party)
https://gist.github.com/e8737bf0e25f843eb8ae17fa69ae4ccc (Android, receiving party)
Message from my notification screen sent around 14:52 local time.

**Comment by michaelkirk** [comment]
Thanks for the details! Fixed in the upcoming release.

**Comment by daz10000** [comment]
THis bug appears to be alive and well.  I just saw it happen from an iOS client that was updated a day ago.  When should the fix have been released?

**Comment by fat-tire** [comment]
Can confirm this is still an issue in 2024.  It has happened now twice.
