### ISSUE TITLE
Some messages are hidden when opening the app

### ISSUE THREAD

**Issue by thenktor** [WhisperSystems/Signal-iOS#667]
If you leave the app with an opened conversation and opened keyboard the next time you re-open the app some messages are hidden because they are "behind" the keyboard.
In this situation the messages should automatically scrolled to the bottom so that you can see the last message.

**Comment by FredericJacobs** [comment]
Should be fixed in next release.

**Comment by thenktor** [comment]
When using third party keyboards (e.g. Minuum or SwiftKey) I'm still having the same issue.
