### ISSUE TITLE
Messages only delivered when app in foreground

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/Signal-iOS#672]
A contact of mine reports that often he will only receive messages when the app is in foreground. As long as it is in background, no messages will be delivered. I can confirm this in so far, as I only get message receipts soon before receiving his answer, which sometimes means waiting a day or two.

Sometimes a background push will happen, but this is very seldomly / not reproducible so far and might still take minutes. (I judge the time it needs for the message to arrive at his phone from the time until I see the delivery receipt.)

**Comment by FredericJacobs** [comment]
This is how push notifications work and the general state of backgrounding on iOS. Nothing we can do about it besides asking new APIs to Apple

**Comment by devurandom** [comment]
He says "other apps" work, and names "email" and "sms" as examples. Do they receive special treatment by iOS?

**Comment by moxie0** [comment]
@devurandom To clarify, are you saying that this person doesn't get a push notification at all?  Or just that the messages aren't actually retrieved until this person clicks on the push notification an opens the app?

**Comment by devurandom** [comment]
Yes, exactly: For the first two or three days he did not receive any push notification at all. Now it magically started to work. He's on iOS 8.1.3.

**Comment by devurandom** [comment]
P.S: Along with reporting that it works now, he also praised Signal for being "lean" and "cool". :)

**Comment by FredericJacobs** [comment]
Please reopen if this continues to occurs again.

**Comment by devurandom** [comment]
The issue appeared again with another user. He installed Signal, exchanged a few messages with me, then he was not notified about new messages for days (don't know yet if he was notified initially). I sent him an SMS to look into Signal, and only after he did, all messages show up as delivered on my TS instance.

Please reopen. (I have no permission to do so.)

**Comment by FredericJacobs** [comment]
This has been an issue in 2.0.2 and should not happen again if he updated.

**Comment by devurandom** [comment]
So I tell him "fixed in 2.0.3"?

**Comment by FredericJacobs** [comment]
Yeah, please let us know if after upgrading to 2.0.3 and having launched the app once, it still happens to him.

**Comment by devurandom** [comment]
Appears to work now: He reacted almost immediately to my message suggesting the update to 2.0.3. :)

**Comment by volcano99** [comment]
All my friends on iOS have the same problem. When I send a message to them it takes hours to be delivered (simply because hours pass before they open Signal...). This is pretty bad considering that they use Signal only with me, so they don't open the app very frequently...

**Comment by FredericJacobs** [comment]
@volcano99 : They get the notification that a "New Message" is received though?

**Comment by volcano99** [comment]
I don't know. What I do know is that the delivery check mark doesn't appear for hours. Maybe you should mark messages as delivered as soon as the "New Message" notification is presented to the iphone user, it would make more sense.

**Comment by FredericJacobs** [comment]
@volcano99: This is a piece of information we don't get from Apple. This is a hard challenge given the restrictions on background tasks on iOS. No end-to-end encrypted messenger that I'm aware of is currently supporting that. We're working on a fix that should be released within the next two weeks! Stay tuned.

**Comment by volcano99** [comment]
Awesome! Thanks!

**Comment by i7u** [comment]
I'm seeing the same issue with volcano99 with all of my Signal contacts using iPads, iPhones 4s/5/6 (all on iOS 8.x). TextSecure contacts don't display this behaviour. Messages to Signal contacts don't get delivered until the user opens Signal (or I give them a Signal call). I talk to people (over GSM voice) who are unaware of whatever I sent them by Signal IM days ago as they have not opened the app and therefore not received the IMs. Looking forward to an updated version that addresses this. If I can provide any helpful data to diagnose this bug do let me know.
