### ISSUE TITLE
Group chat, getting two messages when one is sent

### ISSUE THREAD

**Issue by lloydmeta** [WhisperSystems/Signal-iOS#692]
I have a group chat in which if I invited one of the members, I get 2 messages from her phone every time she sends a message. 

If I leave the group, and she invites me back in, now when I send a message, she gets 2 messages, but I only get one message from her when she sends a message.

**Comment by herrernst** [comment]
I also noticed this bug. I created a group and invited 2 contacts (both on Android). From one contact, I get every message twice.

**Comment by FredericJacobs** [comment]
@herrernst When did you create that group?

**Comment by herrernst** [comment]
March 6th, I think, so most probably 2.0.0.

**Comment by FredericJacobs** [comment]
This should be fixed by now with 2.0.1.
Please feel free to reopen if this occurs again on groups that have been created/updated recently.

**Comment by herrernst** [comment]
Okay, thanks, will try soon, and thank you for your work!

**Comment by MSch** [comment]
Still happening for me with both me and the sender being on 2.0.1. Android sender works correctly.

**Comment by FredericJacobs** [comment]
Yeah, that's because the group probably hasn't been updated since the original corruption.
Shouldn't happen in new groups or after updating the list of members.

**Comment by lloydmeta** [comment]
I would say that this is solved for me; I had to delete and remake the group twice though.

**Comment by MSch** [comment]
@FredericJacobs Thank you, that did fix it. I thought there would be no further user interaction necessary after updating to 2.0.1.
